//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group04_CMS.Common.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Group04_CMS.Common.Global.UIString", typeof(UIString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BreadCrumbCreate {
            get {
                return ResourceManager.GetString("BreadCrumbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string BreadCrumbDetails {
            get {
                return ResourceManager.GetString("BreadCrumbDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BreadCrumbEdit {
            get {
                return ResourceManager.GetString("BreadCrumbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadCrumbHome {
            get {
                return ResourceManager.GetString("BreadCrumbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BreadCrumbSearch {
            get {
                return ResourceManager.GetString("BreadCrumbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string BreadCrumbView {
            get {
                return ResourceManager.GetString("BreadCrumbView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonConfirmDeleteNo {
            get {
                return ResourceManager.GetString("ButtonConfirmDeleteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonConfirmDeleteYes {
            get {
                return ResourceManager.GetString("ButtonConfirmDeleteYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export EXCEL file.
        /// </summary>
        public static string ButtonEXCEL {
            get {
                return ResourceManager.GetString("ButtonEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF file.
        /// </summary>
        public static string ButtonPDF {
            get {
                return ResourceManager.GetString("ButtonPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ButtonViewDetail {
            get {
                return ResourceManager.GetString("ButtonViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Date of Birth.
        /// </summary>
        public static string DatePickerDateOfBirth {
            get {
                return ResourceManager.GetString("DatePickerDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter End Date.
        /// </summary>
        public static string DatePickerEndDate {
            get {
                return ResourceManager.GetString("DatePickerEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Start Date.
        /// </summary>
        public static string DatePickerStartDate {
            get {
                return ResourceManager.GetString("DatePickerStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string DropListSelect {
            get {
                return ResourceManager.GetString("DropListSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttendanceTable.
        /// </summary>
        public static string FieldNameAttendanceTable {
            get {
                return ResourceManager.GetString("FieldNameAttendanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Name.
        /// </summary>
        public static string FieldNameBatch {
            get {
                return ResourceManager.GetString("FieldNameBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string FieldNameBatchId {
            get {
                return ResourceManager.GetString("FieldNameBatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus Name.
        /// </summary>
        public static string FieldNameCampus {
            get {
                return ResourceManager.GetString("FieldNameCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string FieldNameCampusId {
            get {
                return ResourceManager.GetString("FieldNameCampusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string FieldNameClassClassName {
            get {
                return ResourceManager.GetString("FieldNameClassClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string FieldNameClassComment {
            get {
                return ResourceManager.GetString("FieldNameClassComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Year.
        /// </summary>
        public static string FieldNameClassEndYear {
            get {
                return ResourceManager.GetString("FieldNameClassEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string FieldNameClassId {
            get {
                return ResourceManager.GetString("FieldNameClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year.
        /// </summary>
        public static string FieldNameClassStartYear {
            get {
                return ResourceManager.GetString("FieldNameClassStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string FieldNameCode {
            get {
                return ResourceManager.GetString("FieldNameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Name.
        /// </summary>
        public static string FieldNameCollege {
            get {
                return ResourceManager.GetString("FieldNameCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string FieldNameCollegeId {
            get {
                return ResourceManager.GetString("FieldNameCollegeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        public static string FieldNameCreateBy {
            get {
                return ResourceManager.GetString("FieldNameCreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string FieldNameCreateDate {
            get {
                return ResourceManager.GetString("FieldNameCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string FieldNameNote {
            get {
                return ResourceManager.GetString("FieldNameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string FieldNameRole {
            get {
                return ResourceManager.GetString("FieldNameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string FieldNameRoleId {
            get {
                return ResourceManager.GetString("FieldNameRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FieldNameStatus {
            get {
                return ResourceManager.GetString("FieldNameStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FieldNameStatusId {
            get {
                return ResourceManager.GetString("FieldNameStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        public static string FieldNameUpdateBy {
            get {
                return ResourceManager.GetString("FieldNameUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string FieldNameUpdateDate {
            get {
                return ResourceManager.GetString("FieldNameUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string FieldNameUserId {
            get {
                return ResourceManager.GetString("FieldNameUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string FieldNameUserRoleId {
            get {
                return ResourceManager.GetString("FieldNameUserRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ObjectUser {
            get {
                return ResourceManager.GetString("ObjectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TitleDialogConfirmDelete {
            get {
                return ResourceManager.GetString("TitleDialogConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string TitlePageManageLarge {
            get {
                return ResourceManager.GetString("TitlePageManageLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string TitlePageRole {
            get {
                return ResourceManager.GetString("TitlePageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string TitlePageUser {
            get {
                return ResourceManager.GetString("TitlePageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Management.
        /// </summary>
        public static string TitlePageUserRole {
            get {
                return ResourceManager.GetString("TitlePageUserRole", resourceCulture);
            }
        }
    }
}
